appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: cfRMLHW5XPKt2P/b/jd34olefhnh+RA/nPajn4OlIcUap4nLXbloGBNqGPZ4V8ObTPGlC4/BWIILptAWujhpOQNoTmcXI4Ed08eiEFIAKW85qvgowAv4WuC7ZNCB5sPnNGyrzFTdyopRRXEVkZp897hvJ6raiJwJPsxE2dinb0NrUCGSjMhYl4/3KS/eOYjNVFePrxQM4eVvmUgPIEmsmmR6QnOO5MU5pYQZK6icG3k88sK2vsxEgb8rwVtAm08r59fL0oQCcfzmPgp2ekxRn79AraPUMQA3r6SE10fyaQsjjUvf7TKV36d77P0xHZxN9S5BbqMPLnW5G5sYnBTkhmpLo65Hu8DCpuI5zH6w00BFeReee412FiNJkLy75SO/0QHQeALFH+BTXFgeiUrmSoVuDQNNdZkJxknUh3roI+7abQ1URnhbdqJIOvXlCEuvE4EgH3CinhqwEQ7yiyqPEPWaP+/AYNrMEfJncnV5KOI9v8mTDbMBc6bjizhcaKpqQ4XZKTY8Znp+IAhrwTn44pgLDeYLRG8D6cLjgaDiP46EhV09KzaW2ZxOGiv4lB3RfEp5XY4qu/i/m5VUNVN+tOnIREOQIYrRQOHNQWfPm9Rwyd+ZsKo6FxfNfG9vzLF1WSyvXmXOYol31wY/3XEeKOjrHIqhg+v512Yzr5Qhl8Y=}
bot:
  automerge: true
